version: '3'
services:
  flask-app:
    image: nrdyava/flask-app:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
