apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
  name: down-rule
spec:
  groups:
  - name: down
    rules:
    - alert: down 
      expr: kube_pod_status_ready{condition="true",pod=~"todo-flask-app.*"} == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary:  Flask pod failed. Service might be down
        description: Prometheus target missing {{$labels.instance}}
