apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    job: flask-api
    app: flaskapp
spec:
  selector:
    app: flaskapp
  ports:
    - name: web
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 10s
      port: web
      path: /metrics
  selector:
    matchLabels:
      app: flaskapp
         
